// This file is auto-generated by scripts/build.ts
import asset_0 from "./frontend/dist/index.html" with { type: "file" };
import asset_1 from "./frontend/dist/vite.svg" with { type: "file" };
import asset_2 from "./frontend/dist/assets/index-4SxgxBlp.js" with { type: "file" };
import asset_3 from "./frontend/dist/assets/index-km2EF1Jk.css" with { type: "file" };

export const assets: Record<string, any> = {
  "/index.html": asset_0,
  "/vite.svg": asset_1,
  "/assets/index-4SxgxBlp.js": asset_2,
  "/assets/index-km2EF1Jk.css": asset_3
};
