// This file is auto-generated by scripts/build.ts
import asset_0 from "./frontend/dist/assets/index-Ch81U1LN.js" with { type: "file" };
import asset_1 from "./frontend/dist/assets/index-C6NdXrdq.css" with { type: "file" };
import asset_2 from "./frontend/dist/vite.svg" with { type: "file" };
import asset_3 from "./frontend/dist/index.html" with { type: "file" };

export const assets: Record<string, any> = {
  "/assets/index-Ch81U1LN.js": asset_0,
  "/assets/index-C6NdXrdq.css": asset_1,
  "/vite.svg": asset_2,
  "/index.html": asset_3
};
