import { readdir, stat } from "fs/promises";
import { join, relative } from "path";

async function walk(dir: string, fileList: string[] = []) {
    const files = await readdir(dir);
    for (const file of files) {
        const filePath = join(dir, file);
        if ((await stat(filePath)).isDirectory()) {
            await walk(filePath, fileList);
        } else {
            fileList.push(filePath);
        }
    }
    return fileList;
}

const distDir = join(import.meta.dir, "../frontend/dist");
const outputFilePath = join(import.meta.dir, "../embedded_assets.ts");

console.log("Generating embedded assets from:", distDir);

try {
    const files = await walk(distDir);
    let content = "// This file is auto-generated by scripts/build.ts\n";
    let assetMapEntries = [];

    for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const relPath = "/" + relative(distDir, file);
        const varName = `asset_${i}`;
        content += `import ${varName} from "./${relative(join(import.meta.dir, ".."), file)}" with { type: "file" };\n`;
        assetMapEntries.push(`  ${JSON.stringify(relPath)}: ${varName}`);
    }

    content += `\nexport const assets: Record<string, any> = {\n${assetMapEntries.join(",\n")}\n};\n`;

    await Bun.write(outputFilePath, content);
    console.log("Generated:", outputFilePath);
} catch (e) {
    console.error("Failed to generate embedded assets:", e);
    // Write an empty assets map if dist doesn't exist yet
    await Bun.write(outputFilePath, "export const assets: Record<string, any> = {};\n");
}
