# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.filter.outputs.go }}
    steps:
    - uses: actions/checkout@v4

    - uses: dorny/paths-filter@v1
      id: filter
      with:
        filters: |
          go:
            - '**/*.go'
            - 'go.mod'
            - 'go.sum'
            - '.github/workflows/go.yml'

  build:
    needs: check-changes
    if: needs.check-changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
